### ISSUE TITLE
报单录入请求接口（ReqOrderInsertAsync）成功后一直无响应，但失败有响应

### ISSUE THREAD

**Issue by jaic-xiao** [GuanXP/CTPSharp#1]
测试限价买入开仓，调用 var resp = await _api.ReqOrderInsertAsync( req ); 后，如果申报成功，c#代码一直等待无响应，旁边的调试显示若干线程退出，感觉底层像调用c++接口后异常了才有线程退出等提示。 但如果申报不通过，代码能直接拿到响应结果。

**Comment by jaic-xiao** [comment]
代码如下： 		

//await _tdClient.Open_Buy_Limit( "SA309", 1, 2147 );

		TThostFtdcVolumeConditionType volumeCondition = TThostFtdcVolumeConditionType.THOST_FTDC_VC_AV;
            TThostFtdcTimeConditionType timeCondition = TThostFtdcTimeConditionType.THOST_FTDC_TC_GFD;

		var direction = TThostFtdcDirectionType.THOST_FTDC_D_Buy;
		var combOffsetFlag = TThostFtdcOffsetFlagType.THOST_FTDC_OF_Open;
		var orderPriceType = TThostFtdcOrderPriceTypeType.THOST_FTDC_OPT_LimitPrice;

            var req = new CThostFtdcInputOrderField {
                InvestorID = _config.User,
                BrokerID = _config.Broker,
                OrderRef = string.Empty,

                InstrumentID = "SA309",
                Direction = direction,
                CombOffsetFlag = ( (char)combOffsetFlag ).ToString(),
                CombHedgeFlag = ( (char)TThostFtdcHedgeFlagType.THOST_FTDC_HF_Speculation ).ToString(), //投机套保标志(默认投机)

                VolumeTotalOriginal = Math.Abs( 1 ),
                VolumeCondition = volumeCondition,

                MinVolume = 1,
                ForceCloseReason = TThostFtdcForceCloseReasonType.THOST_FTDC_FCC_NotForceClose,
                IsAutoSuspend = 0,
                UserForceClose = 0,
                ContingentCondition = TThostFtdcContingentConditionType.THOST_FTDC_CC_Immediately,
                OrderPriceType = orderPriceType,
                LimitPrice = 2147,
                TimeCondition = timeCondition
            };

		var resp = await _api.ReqOrderInsertAsync( req );

**Comment by GuanXP** [comment]
这是CTP API设计的问题，下单成功只会callback OnRtnOrder 不会callback OnRspOrderInsert.
而所有的async封装API都是依赖 OnRspXXX callback的，所以此异步方法不会返回。规避的方法可以是下列之一

- 加一个超时Task。超时则认为成功，可能不准确
- 不等待 Task完成。此方法会失去错误报告，但一般也没什么问题，因为错误报告多用于调试
- 创建一个TaskCompletionSource, 然后等待 ReqOrderInsertAsync 返回的task和此task二者之一。在 OnRtnOrder 中触发此 task。此方法比较可靠，参考下面的代码
```C#
    // 添加一个类成员来标记下单完成
    private TaskCompletionSource<String>? _triggeredOrder = null;

   // 改进的下单方法
    private async Task<CTPResponse<List<CThostFtdcInputOrderField>>>
    RequestInsertOrderAsync(CThostFtdcInputOrderField req)
    {
        Debug.Assert(_triggeredOrder == null);
        _triggeredOrder?.SetResult("");
        _triggeredOrder = new TaskCompletionSource<string>();
        
        var task = _api!.ReqOrderInsertAsync(req);
        if (await Task.WhenAny(task, _triggeredOrder.Task) == task)
        {
            _triggeredOrder.TrySetCanceled();
            _triggeredOrder = null;
            return await task;
        }
        // 收到 RtnOrder事件就认为下单成功
        var orderRef = await _triggeredOrder.Task;
        Debug.Assert(orderRef == req.OrderRef);
        _triggeredOrder = null;
        return new CTPResponse<List<CThostFtdcInputOrderField>>(null, new() { ErrorID = 0});
    }

    private void OnOrderReturned(CThostFtdcOrderField pOrderField)
    {
        _triggeredOrder?.SetResult(pOrderField.OrderRef); // 在RtnOrder事件处理时完成下单任务
    }
```

**Comment by jaic-xiao** [comment]
> 这是CTP API设计的问题，下单成功只会callback OnRtnOrder 不会callback OnRspOrderInsert. 而所有的async封装API都是依赖 OnRspXXX callback的，所以此异步方法不会返回。规避的方法可以是下列之一
> 
> * 加一个超时Task。超时则认为成功，可能不准确
> * 不等待 Task完成。此方法会失去错误报告，但一般也没什么问题，因为错误报告多用于调试
> * 创建一个TaskCompletionSource, 然后等待 ReqOrderInsertAsync 返回的task和此task二者之一。在 OnRtnOrder 中触发此 task。此方法比较可靠

谢谢，看了官方API文档，的确写着只有错误才OnRsp， 正确是OnRtn，我自己想方式处理代码了。 其实官方细节也有问题，该接口文档上不应该有出现返回0代表成功的网络情况！
